version: '3'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgresql_data:/data

  web:
    build:
      context: .
      dockerfile: DockerfileApp
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=celero.settings.local
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: DockerfileApi
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=celero.settings.local
    ports:
      - "8002:8000"
    volumes:
      - ./api:/api
    depends_on:
      - db
      - web

volumes:
  postgresql_data: